/* Lucide icon registry for the docs shell — nav.ts stores string keys so it
 * stays pure data (client-safe); this maps them to components. Shared by the
 * client sidebar and server pages alike. */
import {
  ArrowLeftRight,
  Banknote,
  Bell,
  BookOpen,
  CalendarCheck,
  CalendarDays,
  Code2,
  CreditCard,
  Database,
  FileText,
  Film,
  FolderOpen,
  Frame,
  Globe,
  HardDrive,
  Images,
  Inbox,
  Info,
  Layers,
  LayoutGrid,
  LifeBuoy,
  Link2,
  ListChecks,
  Lock,
  type LucideIcon,
  Palette,
  Receipt,
  Rocket,
  Sparkles,
  ShieldCheck,
  Smartphone,
  Snowflake,
  User,
  Users,
  Wallet,
} from "lucide-react";

export const DOC_ICONS: Record<string, LucideIcon> = {
  rocket: Rocket,
  sparkles: Sparkles,
  info: Info,
  user: User,
  "shield-check": ShieldCheck,
  bell: Bell,
  inbox: Inbox,
  globe: Globe,
  "calendar-days": CalendarDays,
  "calendar-check": CalendarCheck,
  "layout-grid": LayoutGrid,
  "folder-open": FolderOpen,
  "file-text": FileText,
  images: Images,
  "link-2": Link2,
  frame: Frame,
  film: Film,
  lock: Lock,
  "credit-card": CreditCard,
  layers: Layers,
  receipt: Receipt,
  wallet: Wallet,
  "arrow-left-right": ArrowLeftRight,
  banknote: Banknote,
  users: Users,
  smartphone: Smartphone,
  palette: Palette,
  "code-2": Code2,
  snowflake: Snowflake,
  database: Database,
  "hard-drive": HardDrive,
  "list-checks": ListChecks,
};

export function DocIcon({ icon, className = "h-4 w-4" }: { icon: string; className?: string }) {
  const Icon = DOC_ICONS[icon] ?? BookOpen;
  return <Icon className={className} aria-hidden />;
}
