import { PillSlider } from "@/components/shared/pill-slider";
import { ArrowRight } from "lucide-react";
import Link from "next/link";
import { Style_Script } from "next/font/google";
import { fetchCollections } from "@/lib/actions/collection-actions";
import CollectionGrid from "./(site)/collection/collections-grid";

const styleScript = Style_Script({ weight: "400", subsets: ["latin"] });

export default async function Home() {
  const documents = await fetchCollections({ limit: 6 });
  const trendingDocuments = await fetchCollections({
    limit: 10,
    trending: true,
  });
  return (
    <div className="overflow-x-hidden relative flex flex-col items-center justify-between">
      <div className="lg:max-w-[85rem] h-fit lg:px-2 w-full flex flex-col px-4 py-20">
        <div className="py-16">
          <div className="text-white text-center w-full flex flex-col items-center justify-center font-light text-[5vw] md:text-[3.5vw] leading-tight py-4">
            <h1>
              Backgrounds for your next{" "}
              <span className={`${styleScript.className}`}>project </span> by
              webcules, generated by AI
            </h1>
            <h2 className="w-3/4 text-[2.5vw] md:text-[1.5vw] py-4 text-slate-200">
              Unlock a Vast Collection of AI-Generated Backgrounds, Perfect for
              Enhancing Your Creative Projects with High-Quality, Ready-to-Use
              Visuals by{" "}
              <span>
                <Link href="https://webcules.com" className="text-indigo-500">
                  Webcules.
                </Link>
              </span>
            </h2>
            <PillSlider
              className="w-1/4 h-16 rounded-full my-6"
              images={[
                "/lumina-9.jpg",
                "/lumina-6.jpg",
                "/lumina-12.jpg",
                "/lumina-4.jpg",
              ]}
              overlayClassName="bg-black/50"
            >
              bg
            </PillSlider>
            <div className="absolute z-[-1] flex place-items-center before:absolute before:h-[300px] before:-translate-x-3/4 before:rounded-full before:bg-gradient-radial before:from-indigo-400 before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:translate-x after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:w-[480px] after:w-[240px] before:lg:h-[360px]"></div>
          </div>
        </div>
        <div className="py-8">
          <div className="flex justify-between items-center">
            <span className="anim whitespace-nowrap rounded-3xl bg-darkest px-2.5 py-1.5 text-sm text-gray-50 border-gray-50 border">
              Browse Collections
            </span>
            <Link
              href={"/collection"}
              className="flex flex-row items-center whitespace-nowrap rounded-3xl bg-darkest text-sm text-gray-50 border-gray-700 hover:border-white/20 border px-2"
            >
              See All
              <ArrowRight />
            </Link>
          </div>
          <CollectionGrid documents={documents} />
        </div>
        <div className="py-8">
          <div className="flex justify-between items-center">
            <span className="anim whitespace-nowrap rounded-3xl bg-darkest px-2.5 py-1.5 text-sm text-gray-50 border-gray-50 border">
              Recently trending
            </span>
            <Link
              href={"/updates"}
              className="flex flex-row items-center whitespace-nowrap rounded-3xl bg-darkest text-sm text-gray-50 border-gray-700 hover:border-white/20 border px-2"
            >
              See All
              <ArrowRight />
            </Link>
          </div>
          <CollectionGrid documents={trendingDocuments} />
        </div>
      </div>
    </div>
  );
}
