import Link from "next/link";
import { ArrowLeft, Lock, Image as Photo } from "lucide-react";
import Image from "next/image";
import { fetchCollectionImageId } from "@/lib/actions/bg-image-actions";
import { getUserPurchases } from "@/lib/actions/purchase-actions";
import { Media } from "@webcules/payload/components/Media";
import { CTAButton } from "@/components/shared/cta-button";
import { DownloadButton } from "@/components/shared/download-button";
import { checkUserAuth } from "@/lib/actions/auth-actions";

export default async function ImagePage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id: imageId } = await params;
  const authStatus = await checkUserAuth();
  const imageDoc = await fetchCollectionImageId(imageId);
  const isPremium = (imageDoc.singleImagePrice ?? 0) > 0;

  // Check user's purchases and access
  let userPurchases = null;
  let canDownloadImage = false;

  if (authStatus.user?.id) {
    userPurchases = await getUserPurchases(authStatus.user.id.toString());

    // User can download if they have active subscription or purchased this image
    canDownloadImage =
      (userPurchases.isPaid && userPurchases.subscriptionStatus === "active") ||
      userPurchases.purchases.some(
        (purchase) =>
          purchase.itemType === "media" &&
          purchase.item?.relationTo === "backgroundMedia" &&
          purchase.item?.value === parseInt(imageId)
      );
  }

  const fileSizeMB = ((imageDoc.filesize ?? 0) / 1024 / 1024).toFixed(1);
  const imageResolution = `${imageDoc.width}x${imageDoc.height}`;
  const fileType = imageDoc.mimeType?.split("/")[1]?.toUpperCase() || "N/A";
  const displayPrice =
    imageDoc.singleImagePrice?.toFixed(2) || "(just kidding, its free)";
  const baseUrl = process.env.NEXT_PUBLIC_SERVER_URL || "http://localhost:3000";
  return (
    <div className="overflow-x-hidden relative flex flex-col items-center justify-between">
      <div className="lg:max-w-[85rem] h-fit lg:px-16 w-full flex flex-col px-4 py-20 mt-20">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
          <div className="flex flex-col relative items-start justify-end h-80 w-full rounded-xl border-white/20 border-[0.25px] hover:border-white/30 hover:border-2 overflow-clip">
            <div className="bg-gradient-to-t from-black to-transparent absolute w-full h-full z-10">
              {isPremium && <Lock size={32} className="mx-4 my-4 text-white" />}
            </div>
            <Media
              resource={imageDoc}
              alt={imageDoc?.alt || "an image generated by AI for web design"}
              fill
              imgClassName="bg-black object-cover"
            />
          </div>
          <div className="flex flex-col items-start gap-y-6">
            <Link
              href={"/"}
              className="flex flex-row items-center whitespace-nowrap rounded-3xl bg-darkest text-sm text-gray-50 border-gray-700 hover:border-white/20 border py-2 px-4"
            >
              <ArrowLeft />
              Back
            </Link>
            <div className="flex w-full gap-x-4 items-start md:items-end justify-between">
              <h1 className="text-2xl md:text-5xl text-white">
                {imageDoc.relatedCollection.title.replace("-", " ")}
              </h1>
              <div className="text-sm text-gray-400">
                Check out others in the
                <Link
                  href={`/collection/${imageDoc.relatedCollection.id}`}
                  className="text-white underline mx-1"
                >
                  {imageDoc.relatedCollection.title}
                </Link>
                collection
              </div>
            </div>
            <div className="rounded-lg bg-white/10 w-full h-fit flex flex-col p-4 divide-y-[1px] divide-white/20 gap-y-4">
              <div className="flex flex-row items justify-between w-full text-gray-400 gap-4 py-2">
                <div className="flex flex-row gap-2">
                  <div className="w-7 h-7 relative">
                    <Image
                      src={"/midjourney-icon.png"}
                      fill
                      alt="midjourney logo"
                      style={{ objectFit: "contain" }}
                    />{" "}
                  </div>
                  Prompt
                </div>
                {canDownloadImage ? (
                  <div className="w-2/3">
                    <p>{imageDoc.relatedCollection.midjourneyPrompt}</p>
                  </div>
                ) : (
                  <div className="blur-[8px] w-2/3 ">
                    <p className="truncate">
                      this is the midjourney prompt, that will unlock once
                      subscribed, this was hard to get. So many tries
                    </p>
                  </div>
                )}
              </div>
              <div className="flex flex-row items justify-between w-full text-gray-400 gap-4 py-2">
                <div className="flex flex-row gap-2">File type</div>
                <div className="flex flex-row gap-2">
                  <Photo />
                  <p>{fileType}</p>
                </div>
              </div>
              <div className="flex flex-row items justify-between w-full text-gray-400 gap-4 py-2">
                <div className="flex flex-row gap-2">Image Resolution</div>
                <div className="flex flex-row gap-2">
                  <p>{imageResolution}</p>
                </div>
              </div>
            </div>
            {canDownloadImage ? (
              <DownloadButton
                type="single"
                downloadUrl={baseUrl + imageDoc.url || ""}
                filename={imageDoc.filename || `image_${imageId}.jpg`}
                fileSize={`${fileSizeMB} MB`}
                userId={authStatus.user?.id?.toString() || ""}
                itemId={imageId}
              />
            ) : (
              isPremium && (
                <div className="flex flex-col w-full sm:flex-row gap-4 text-white">
                  {authStatus.user?.subscriptionStatus != "active" && (
                    <>
                      <CTAButton
                        type="backgroundImage"
                        price={displayPrice}
                        item={imageDoc}
                      />
                      <CTAButton type="subscription" />
                    </>
                  )}
                </div>
              )
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
