// generated by: social sync — do not edit by hand (add/edit demos in src/demos/<slug>.tsx, then re-run)
import type { ComponentType } from "react";

export type DemoEntry = {
  meta: DemoMeta;
  load: () => Promise<{ default: ComponentType<{ variant?: string; layout?: string; hook?: string; panel?: boolean }> }>;
};
export type DemoMeta = { slug: string; title: string; component: string; description: string };

export const demos: Record<string, DemoEntry> = {
  "neural-pathways": { meta: {
      "slug": "neural-pathways",
      "title": "Neural Pathways",
      "component": "neural-pathways",
      "description": "Dual-waist light-stream lens, fully parametric SVG — ?panel=1 exposes every prop live"
    }, load: () => import("./neural-pathways.tsx") },
};
