#!/usr/bin/env node
/* WEB-320 — assemble the seed-template registry from the authored drafts in
 * tools/seed-drafts/*.json into lib/seed-templates.ts (typed, committed).
 * Single writer: the drafts are the design-craft source of truth (authored
 * + visually verified against the harness); this script is the mechanical
 * copy. Re-run after any draft change, then re-run
 * tools/render-template-previews.mjs to refresh picker thumbs.
 *
 *   node tools/assemble-seeds.mjs   (validates each draft through the
 *                                    canonical parse expectations: template
 *                                    marker === key, sections present) */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = join(fileURLToPath(import.meta.url), "..", "..");
const DRAFTS = join(appRoot, "tools", "seed-drafts");

const drafts = readdirSync(DRAFTS)
  .filter((f) => f.endsWith(".json"))
  .map((f) => JSON.parse(readFileSync(join(DRAFTS, f), "utf8")))
  .sort((a, b) => a.key.localeCompare(b.key));

const errs = [];
for (const d of drafts) {
  if (d.key !== d.design?.template) errs.push(`${d.key}: design.template (${d.design?.template}) must equal key`);
  if (!Array.isArray(d.design?.sections) || d.design.sections.length === 0) errs.push(`${d.key}: no sections`);
  if (!Array.isArray(d.genres) || d.genres.length === 0) errs.push(`${d.key}: no genres`);
  if (typeof d.description !== "string" || !d.description) errs.push(`${d.key}: no description`);
}
if (errs.length) {
  console.error(errs.join("\n"));
  process.exit(1);
}

// Category ordering for the picker: wedding, family, party, corporate, editorial, minimal.
const order = ["wedding", "family", "party", "corporate", "editorial", "minimal"];
const sorted = [...drafts].sort((a, b) => order.indexOf(a.category) - order.indexOf(b.category) || a.key.localeCompare(b.key));

const entry = (d) => `  {
    key: ${JSON.stringify(d.key)},
    name: ${JSON.stringify(d.name)},
    category: ${JSON.stringify(d.category)},
    description: ${JSON.stringify(d.description)},
    genres: ${JSON.stringify(d.genres)},
    harnessAccent: ${JSON.stringify(d.harnessAccent ?? "")},
    design: ${JSON.stringify(d.design)},
  },`;

const ts = `/* GENERATED by tools/assemble-seeds.mjs from tools/seed-drafts/ — do not
 * edit here; fix the draft and re-run the script (then refresh picker thumbs
 * with tools/render-template-previews.mjs). Each seed was authored visually
 * against the sample pack (/dev/template-harness) and passed the render gate
 * + independent visual verification (WEB-320). */

import type { GalleryDesign } from "./gallery-design";
import type { SampleGenre } from "./sample-pack";

export type SeedTemplate = {
  /** Slug — also the design's \`template\` marker until customized. */
  key: string;
  name: string;
  category: "wedding" | "family" | "party" | "corporate" | "editorial" | "minimal";
  /** One line for the picker card. */
  description: string;
  /** The sample genres this seed is photographed with in previews/thumbs. */
  genres: SampleGenre[];
  /** Demo accent for harness/thumbnail renders only (real studios use their brand). */
  harnessAccent: string;
  design: GalleryDesign;
};

export const SEED_TEMPLATES: SeedTemplate[] = [
${sorted.map(entry).join("\n")}
];

export function seedTemplateOf(key: string): SeedTemplate | null {
  return SEED_TEMPLATES.find((t) => t.key === key) ?? null;
}

/* ---------------- apply semantics (WEB-320) ---------------- */

/** Remap a seed's sample-photo references onto a real project's photos:
 * hero images and picks/collage items are positional (the project's first N
 * photos in delivery order stand in for the sample picks), rating bindings
 * survive as-is (they work on any gallery), folder bindings widen to "all".
 * The seed KEY travels with the design (a pristine application is free-tier
 * saveable; the builder clears it on first edit). Photos shorter than the
 * seed's picks simply render fewer items. */
export function adaptSeedToProject(
  seed: SeedTemplate,
  photoIds: string[],
): GalleryDesign {
  let i = 0;
  /** Positional stand-ins, wrapping for short galleries (sections are
   * independent surfaces; reuse beats empty states). Empty gallery → []. */
  const take = (n: number): string[] =>
    photoIds.length === 0 ? [] : Array.from({ length: n }, () => photoIds[i++ % photoIds.length]);
  const design: GalleryDesign = JSON.parse(JSON.stringify(seed.design));
  design.template = seed.key;
  for (const s of design.sections ?? []) {
    if (s.type === "hero") {
      const n = Math.max(1, s.images.length);
      s.images = take(n).map((assetId, idx) => ({ assetId, focal: s.images[idx]?.focal ?? { x: 0.5, y: 0.4 } }));
    } else if (s.type === "gallery" || s.type === "slideshow") {
      if (s.binding.kind === "picks") s.binding = { kind: "picks", ids: take(s.binding.ids.length) };
      else if (s.binding.kind === "folder") s.binding = { kind: "all" };
    } else if (s.type === "collage") {
      s.items = s.items.map((it) => ({ ...it, assetId: take(1)[0] ?? it.assetId }));
    }
  }
  return design;
}
`;

writeFileSync(join(appRoot, "lib", "seed-templates.ts"), ts);
console.log(`lib/seed-templates.ts assembled — ${sorted.length} seeds: ${sorted.map((d) => d.key).join(", ")}`);
