#!/usr/bin/env node
/* WEB-319 — sample-pack uploader. Idempotent: reads tools/sample-pack.json
 * (written by tools/generate-sample-pack.py), uploads the thumb (480px) and
 * web (2048px) derivatives to BOTH buckets (snap-staging, snap-webcules) at
 * platform-wide `samples/{genre}/{thumb|web}/{name}.jpg` keys, and emits
 * lib/sample-pack.ts (the typed manifest the harness + preview pipeline
 * render against). Masters stay local — never uploaded.
 *
 * Usage:  node tools/upload-samples.mjs [--env staging|prod|both] [--emit-only] */
import { execFile as execFileCb } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const execFile = promisify(execFileCb);
const here = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(here, "..");

const args = process.argv.slice(2);
const envs = args.includes("--both")
  ? ["staging", "prod"]
  : [...(args.includes("--staging") ? ["staging"] : []), ...(args.includes("--prod") ? ["prod"] : []), ...(args.includes("--local") ? ["local"] : [])];
if (!envs.length) envs.push("staging", "prod");
const emitOnly = args.includes("--emit-only");

const BUCKETS = { local: "snap-webcules", staging: "snap-staging", prod: "snap-webcules" };
const manifest = JSON.parse(readFileSync(join(appRoot, "tools", "sample-pack.json"), "utf8"));

/* ---- emit lib/sample-pack.ts (typed manifest) ---- */
const genres = Object.keys(manifest.genres);
const lines = [];
for (const genre of genres) {
  const photos = manifest.genres[genre].map((e) => {
    const long = Math.max(e.width, e.height);
    const w = Math.round((e.width * 2048) / long);
    const h = Math.round((e.height * 2048) / long);
    return `    { id: ${JSON.stringify(e.name)}, genre: ${JSON.stringify(genre)}, filename: ${JSON.stringify(`${e.name}.jpg`)}, thumb: ${JSON.stringify(`/api/pack/samples/${genre}/thumb/${e.name}.jpg`)}, web: ${JSON.stringify(`/api/pack/samples/${genre}/web/${e.name}.jpg`)}, width: ${w}, height: ${h} },`;
  });
  lines.push(`  ${JSON.stringify(genre)}: [\n${photos.join("\n")}\n  ],`);
}
const ts = `/* GENERATED by tools/upload-samples.mjs from tools/sample-pack.json — do
 * not edit. The Template Studio sample photography (AI-generated, SDXL — no
 * model release required, never attributed to a real studio; license note
 * lives in the manifest). The harness + preview pipeline render templates
 * against these; galleries never ship them. */${"\n"}
export type SamplePhoto = {
  id: string;
  genre: SampleGenre;
  filename: string;
  /** 480px derivative (grid tiles). */
  thumb: string;
  /** 2048px derivative (heroes/previews). */
  web: string;
  width: number;
  height: number;
};

export const SAMPLE_GENRES = ${JSON.stringify(genres)} as const;
export type SampleGenre = (typeof SAMPLE_GENRES)[number];

export const SAMPLE_PACK: Record<SampleGenre, SamplePhoto[]> = {
${lines.join("\n")}
};

/** Every sample photo in a stable order (genres in registry order). */
export const ALL_SAMPLES: SamplePhoto[] = SAMPLE_GENRES.flatMap((g) => SAMPLE_PACK[g]);
`;
writeFileSync(join(appRoot, "lib", "sample-pack.ts"), ts);
console.log(`lib/sample-pack.ts emitted (${genres.length} genres, ${genres.reduce((n, g) => n + manifest.genres[g].length, 0)} photos)`);

if (emitOnly) process.exit(0);

/* ---- upload derivatives ---- */
const uploads = [];
for (const [genre, entries] of Object.entries(manifest.genres)) {
  for (const e of entries) {
    for (const variant of ["thumb", "web"]) {
      uploads.push({ key: `samples/${genre}/${variant}/${e.name}.jpg`, file: join(appRoot, "tools", "sample-pack", e.paths[variant]) });
    }
  }
}
console.log(`uploading ${uploads.length} objects to: ${envs.map((e) => BUCKETS[e]).join(", ")}`);

for (const env of envs) {
  let n = 0;
  for (const { key, file } of uploads) {
    // local = the dev wrangler R2 simulator (no --remote) — powers the
    // offline harness; staging/prod are the real buckets.
    const flags = ["wrangler", "r2", "object", "put", `${BUCKETS[env]}/${key}`, "--file", file, "--content-type", "image/jpeg"];
    // local: a dedicated persist dir the harness worker also uses
    // (npx wrangler dev --config dist/server/wrangler.json --persist-to tools/.harness-state)
    if (env === "local") flags.push("--persist-to", "tools/.harness-state");
    if (env !== "local") flags.push("--remote");
    await execFile("npx", flags, { cwd: appRoot, shell: process.platform === "win32" });
    if (++n % 20 === 0) console.log(`  [${env}] ${n}/${uploads.length}`);
  }
  console.log(`[${env}] done — ${n} objects`);
}
