[phases.setup]
nixPkgs = ['nodejs_20', 'nodePackages.pnpm'] 

[phases.install]
cmds = ['corepack enable pnpm', 'pnpm install --frozen-lockfile']

[phases.build]
cmds = [
  'pnpm run generate:types',  # Generate Payload types (if required)
  'pnpm run build'  # Your Next.js build
]

[phases.start]
cmd = 'pnpm run start' 

[staticAssets]
sourceDirectory = '.next'

[vars]
NODE_ENV = 'production'
NODE_OPTIONS = '--no-deprecation'