import path from "node:path";

/**
 * Local storage layer. The original site fetched prebuilt JSON and PNG assets
 * from a public object-storage bucket; this rebuild ships the exact same file
 * layout inside `public/storage/`, generated by `pipeline/build-storage.mjs`.
 * Server components read the files from disk at build time; client components
 * fetch them over the same origin from `/storage/...`.
 */
export const PUBLIC_STORAGE_BASE_URL = "/storage";
export const STORAGE_DIR = path.join(process.cwd(), "public", "storage");

export const PAPER_CATALOG_URL = `${PUBLIC_STORAGE_BASE_URL}/catalog.json`;
export const HOMEPAGE_DATA_URL = `${PUBLIC_STORAGE_BASE_URL}/homepage.json`;
export const MOST_CITED_DATA_URL = `${PUBLIC_STORAGE_BASE_URL}/most-cited.json`;
export const MOST_STARRED_DATA_URL = `${PUBLIC_STORAGE_BASE_URL}/most-starred.json`;
export const SEARCH_INDEX_URL = `${PUBLIC_STORAGE_BASE_URL}/search-index.json`;

export function paperAssetUrl(paperId: string, asset: "cover" | "social") {
  return `${PUBLIC_STORAGE_BASE_URL}/papers/${encodeURIComponent(paperId)}/${asset}.png`;
}

export function paperSummaryPath(paperId: string) {
  return `papers/${encodeURIComponent(paperId)}/summary.json`;
}

export function topicArtUrl(topicId: string) {
  return `${PUBLIC_STORAGE_BASE_URL}/topics/${encodeURIComponent(topicId)}/art.png`;
}

export function storageRelativePath(url: string) {
  return url.replace(`${PUBLIC_STORAGE_BASE_URL}/`, "");
}

/** Reads a storage JSON file from disk (server components, build time). */
export async function readStorageJson<T>(relativePath: string): Promise<T> {
  const { readFile } = await import("node:fs/promises");
  const filePath = path.join(STORAGE_DIR, relativePath);
  return JSON.parse(await readFile(filePath, "utf8")) as T;
}
