// Generated by `pnpm topics:sync` from src/topic-taxonomy.ts — do not edit by hand.

export type TopicSection = { slug: string; label: string; accent: string; artworkSlug: string };
export type TopicDefinition = { slug: string; section: string; label: string; description: string };

export const TOPIC_SECTIONS: TopicSection[] = [
  { slug: "reasoning", label: "Reasoning", accent: "blue", artworkSlug: "reasoning" },
  { slug: "agents", label: "Agents", accent: "orange", artworkSlug: "agents" },
  { slug: "multimodal", label: "Multimodal", accent: "pink", artworkSlug: "multimodal" },
  { slug: "video-spatial", label: "Video and spatial AI", accent: "red", artworkSlug: "video-generation" },
  { slug: "systems", label: "Systems and efficiency", accent: "cyan", artworkSlug: "systems" },
  { slug: "robotics", label: "Robotics and embodied AI", accent: "yellow", artworkSlug: "robotics" },
  { slug: "science", label: "Science and medicine", accent: "violet", artworkSlug: "science" },
  { slug: "safety", label: "Safety and analysis", accent: "blue", artworkSlug: "safety" },
];

export const TOPIC_TAXONOMY: TopicDefinition[] = [
  {
    slug: "reasoning-methods",
    section: "reasoning",
    label: "Reasoning methods",
    description: "Techniques that improve how a model deliberates: chain-of-thought, latent or implicit reasoning, self-consistency, thinking budgets, and knowing when to stop thinking.",
  },
  {
    slug: "rl-for-reasoning",
    section: "reasoning",
    label: "RL for reasoning",
    description: "Reinforcement learning applied to train reasoning ability, including RLVR, verifiable rewards, reward design, and exploration for reasoning models.",
  },
  {
    slug: "agent-training",
    section: "agents",
    label: "Agent training and self-evolution",
    description: "Training agents: environment synthesis, self-evolving and self-improving agent loops, agent RL frameworks, and agent post-training recipes.",
  },
  {
    slug: "agent-benchmarks",
    section: "agents",
    label: "Agent benchmarks and computer use",
    description: "Evaluating agents on realistic tasks: computer-use and GUI agents, tool-use benchmarks, long-horizon task suites, and agent safety evaluation.",
  },
  {
    slug: "coding-agents",
    section: "agents",
    label: "Coding agents",
    description: "Software engineering with LLMs: SWE-style agents and harnesses, repository-level bug fixing, code generation models, and coding benchmarks.",
  },
  {
    slug: "search-agents",
    section: "agents",
    label: "Search and deep research",
    description: "Information-seeking agents: deep research systems, open-web search agents, retrieval-augmented agents, and their training data and benchmarks.",
  },
  {
    slug: "agent-skills",
    section: "agents",
    label: "Agent skills and memory",
    description: "Reusable agent capability: skill acquisition, distillation and libraries, procedural memory, and transferable lessons from trajectories.",
  },
  {
    slug: "long-context",
    section: "systems",
    label: "Long context and attention",
    description: "Extending or serving long context: sparse and linear attention architectures, KV-cache compression, memory-augmented generation, and long-context training.",
  },
  {
    slug: "diffusion-lms",
    section: "systems",
    label: "Diffusion LMs and decoding",
    description: "Diffusion and non-autoregressive language models, parallel and speculative decoding, and sampling or decoding strategies.",
  },
  {
    slug: "model-efficiency",
    section: "systems",
    label: "Efficiency and serving",
    description: "Making models cheaper to train or run: distillation, quantization, sparsity, mixture-of-experts, inference engines, and serving systems.",
  },
  {
    slug: "model-architecture",
    section: "systems",
    label: "Model architecture",
    description: "Novel model architectures as the contribution: attention alternatives, linear and state-space models, hybrid or recurrent designs, biologically motivated architectures, and architectural scaling studies.",
  },
  {
    slug: "data-curation",
    section: "systems",
    label: "Data and synthetic generation",
    description: "Training data itself: pretraining corpus construction, synthetic data generation, data filtering, deduplication, and data mixture studies.",
  },
  {
    slug: "interpretability-analysis",
    section: "safety",
    label: "Interpretability and analysis",
    description: "Understanding why models behave as they do: mechanistic interpretability, sparse autoencoders, probing, scaling and empirical laws, emergent phenomena, and hallucination analyses.",
  },
  {
    slug: "vlm-architectures",
    section: "multimodal",
    label: "Vision-language models",
    description: "Multimodal LLM architecture and training: unified understanding and generation, visual representation alignment, and general-purpose VLM technical reports.",
  },
  {
    slug: "image-generation",
    section: "multimodal",
    label: "Image generation and editing",
    description: "Text-to-image and image-editing models: diffusion transformers, autoregressive image models, and image generation foundation models.",
  },
  {
    slug: "video-generation",
    section: "video-spatial",
    label: "Video generation and world models",
    description: "Generating or simulating video: long-form and interactive video generation, controllable video synthesis, and generative video world models.",
  },
  {
    slug: "video-understanding",
    section: "video-spatial",
    label: "Video understanding",
    description: "Comprehending existing video: video question answering, temporal grounding, video reasoning, and video understanding benchmarks.",
  },
  {
    slug: "spatial-3d",
    section: "video-spatial",
    label: "3D and spatial intelligence",
    description: "3D and 4D scene generation, reconstruction, spatial reasoning, point clouds, and 3D detection or perception.",
  },
  {
    slug: "document-ocr",
    section: "multimodal",
    label: "Document AI and OCR",
    description: "Document parsing and intelligence: OCR models, layout and table extraction, document-to-markdown conversion, and visual document understanding.",
  },
  {
    slug: "audio-speech",
    section: "multimodal",
    label: "Audio, speech, and omni-modal",
    description: "Speech recognition and synthesis, music and audio generation, and omni-modal models that jointly handle audio with text or vision.",
  },
  {
    slug: "robot-policies",
    section: "robotics",
    label: "Robot policies",
    description: "Vision-language-action models, robot manipulation and navigation policies, embodied control, and robot learning from demonstration or simulation.",
  },
  {
    slug: "science-medicine",
    section: "science",
    label: "Science and medicine",
    description: "AI applied to scientific and medical domains: scientific foundation models, discovery and hypothesis generation, clinical reasoning, and medical imaging.",
  },
  {
    slug: "research-automation",
    section: "science",
    label: "Research automation",
    description: "Automating the research workflow itself: paper writing and review assistance, literature synthesis, and paper-to-artifact generation.",
  },
  {
    slug: "safety-alignment",
    section: "safety",
    label: "Safety and alignment",
    description: "Making models behave: alignment and preference-tuning methods, jailbreak and adversarial robustness, guardrails and refusal behaviour, and misuse or societal-risk evaluation.",
  },
];
