// A deterministic stand-in music bed, synthesised at an exact BPM.
//
// This is NOT the real soundtrack. The real one is generated by ACE-Step in ComfyUI (see comfy.mjs). The stand-in exists so that
// the whole beat-sync pipeline (analysis, alignment, mixing, QC) can be tested and demonstrated without a model installed, and so
// a reel can still get a music version when the rig is offline. It is declared as engine "standin" in music.json, always.

import { SR } from "../edit/sfx.mjs";

const TAU = Math.PI * 2;

function rng(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Dark, driving trailer-style bed in A minor: heartbeat kick, sub pulse, off-beat hats, a swelling pad and a plucked arpeggio. Mono. */
export function standinBed({ bpm, seconds, seed = 1, phase_s = 0 }) {
  const n = Math.round(seconds * SR);
  const out = new Float32Array(n);
  const rnd = rng(seed);
  const p = 60 / bpm;
  const add = (t0, fn, len) => {
    const i0 = Math.round(t0 * SR);
    for (let i = 0; i < len && i0 + i < n; i++) if (i0 + i >= 0) out[i0 + i] += fn(i / SR);
  };

  const beats = Math.ceil((seconds - phase_s) / p) + 1;
  for (let k = 0; k < beats; k++) {
    const t = phase_s + k * p;
    const bar = Math.floor(k / 4);
    const inBar = k % 4;
    // heartbeat kick: strong on 1 and 3, softer on 2 and 4
    const kg = inBar === 0 ? 0.95 : inBar === 2 ? 0.8 : 0.5;
    add(t, (x) => kg * Math.sin(TAU * (48 + 70 * Math.exp(-x / 0.022)) * x) * Math.exp(-x / 0.11), Math.round(0.4 * SR));
    // sub pulse on every eighth, the root of A minor
    for (const h of [0, 0.5]) {
      const bt = t + h * p;
      add(bt, (x) => 0.38 * (Math.sin(TAU * 55 * x) + 0.35 * Math.sin(TAU * 110 * x)) * Math.exp(-x / (0.16 * p / 0.5)), Math.round(p * SR));
    }
    // off-beat hat (filtered noise)
    {
      let lp = 0;
      add(t + p / 2, (x) => {
        const w = rnd() * 2 - 1;
        lp += 0.6 * (w - lp);
        return 0.16 * (w - lp) * Math.exp(-x / 0.025);
      }, Math.round(0.08 * SR));
    }
    // plucked arpeggio from bar 2: 16ths over A C E A
    if (bar >= 2) {
      const notes = [220, 261.63, 329.63, 440];
      for (let s = 0; s < 4; s++) {
        const f = notes[(k + s) % 4];
        add(t + (s * p) / 4, (x) => 0.1 * (Math.sin(TAU * f * x) + 0.4 * Math.sin(TAU * 2 * f * x)) * Math.exp(-x / 0.09), Math.round(0.25 * SR));
      }
    }
    // a snare-like clap on 2 and 4 from bar 1
    if (bar >= 1 && (inBar === 1 || inBar === 3)) {
      let lp = 0;
      add(t, (x) => {
        const w = rnd() * 2 - 1;
        lp += 0.35 * (w - lp);
        return 0.3 * lp * Math.exp(-x / 0.07) + 0.2 * Math.sin(TAU * 190 * x) * Math.exp(-x / 0.05);
      }, Math.round(0.3 * SR));
    }
  }

  // pad: detuned saws on the A minor chord, swelling every two bars
  const chord = [110, 130.81, 164.81];
  let lp = 0;
  for (let i = 0; i < n; i++) {
    const t = i / SR;
    const swell = 0.5 - 0.5 * Math.cos(TAU * (t / (8 * p)));
    let s = 0;
    for (const f of chord) for (const d of [0.995, 1.005]) s += 2 * ((t * f * d) % 1) - 1;
    lp += 0.04 * (s - lp);
    out[i] += 0.07 * (0.35 + 0.65 * swell) * lp;
  }

  // overall build across the first four bars, gentle soft clip so peaks stay controlled
  const build = 4 * 4 * p;
  for (let i = 0; i < n; i++) {
    const g = 0.55 + 0.45 * Math.min(1, i / SR / build);
    out[i] = Math.tanh(out[i] * g * 1.2);
  }
  return out;
}
