import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { REPO_ROOT, SOCIAL_ROOT, ensureDir, flagStr, log, readManifest, writeManifest, type Args } from "./util.ts";

const LANDING = path.join(REPO_ROOT, "apps", "landing");

const prettyName = (slug: string) =>
  slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()).replace(/\s+/g, "");

/** Publish a component into the Webcules landing library (library.json + preview + registry). */
export async function cmdPublish(args: Args) {
  const slug = flagStr(args, "project");
  if (!slug) log.err("usage: social publish --project <slug> [--title X] [--tagline '...'] [--tags a,b,c]") || process.exit(1);
  const m = readManifest(slug);
  if (!m.component.name || !m.component.file) {
    log.err("manifest has no component yet — build it first (PLAYBOOK.md phase 3)");
    process.exit(1);
  }

  const name = m.component.name;
  const title = flagStr(args, "title") ?? m.component.title ?? prettyName(name);
  const tagline = flagStr(args, "tagline") ?? (m.component.description ?? "").split(/(?<=\.)\s/)[0] ?? "";
  const tags = flagStr(args, "tags")?.split(",").map((t) => t.trim()) ?? ["svg", "animation", "background"];

  // 1) preview webp → landing public/components/<slug>.webp
  const previewSrc = path.join(SOCIAL_ROOT, slug, "docs", `${slug}-preview.webp`);
  const previewDst = path.join(LANDING, "public", "components", `${slug}.webp`);
  if (fs.existsSync(previewSrc)) {
    ensureDir(path.dirname(previewDst));
    fs.copyFileSync(previewSrc, previewDst);
    log.ok(`preview copied → apps/landing/public/components/${slug}.webp`);
  } else {
    log.warn(`no preview at webcules/social/${slug}/docs/${slug}-preview.webp — run scripts/preview.ts first`);
  }

  // 2) library.json entry (add or refresh placement; existing copy is preserved)
  const libPath = path.join(LANDING, "components", "library", "library.json");
  const lib = JSON.parse(fs.readFileSync(libPath, "utf8"));
  const existing = lib.components.find((c: any) => c.name === name);
  const entry: any = existing ?? {
    name,
    title,
    tagline,
    description: m.component.description ?? tagline,
    tags,
    premium: false,
    phase: "approved",
    docsMode: "generated",
  };
  entry.preview = `/components/${slug}.webp`;
  entry.phase = "approved";
  if (!existing) lib.components.push(entry);
  fs.writeFileSync(libPath, JSON.stringify(lib, null, 2) + "\n");
  log.ok(`library entry: components/library/library.json → ${name}`);

  // 3) regenerate manifest.gen.ts (deterministic, same format as forge:approve)
  const header = `/* AUTO-GENERATED by \`pnpm forge:approve\` — edit library.json instead. */
export type LibraryEntry = {
  name: string;
  title: string;
  tagline: string;
  description: string;
  tags: string[];
  premium: boolean;
  phase: "draft" | "approved";
  docsMode: "custom" | "generated";
  preview?: string;
  phrase?: string;
};

`;
  fs.writeFileSync(
    path.join(LANDING, "components", "library", "manifest.gen.ts"),
    header + "export const LIBRARY: LibraryEntry[] = " + JSON.stringify(lib.components, null, 2) + ";\n",
  );
  log.ok("manifest.gen.ts regenerated");

  // 4) rebuild the /r registry JSONs
  const build = spawnSync("node", ["scripts/build-registry.mjs"], { cwd: LANDING, stdio: "inherit", shell: process.platform === "win32" });
  if (build.status !== 0) {
    log.err("registry build failed");
    process.exit(1);
  }

  // 5) docs README → registry docs field stays short; record paths in manifest
  m.status = "packaged";
  m.component.docs = `webcules/social/${slug}/docs/README.md`;
  m.component.preview = `webcules/social/${slug}/docs/${slug}-preview.webp`;
  writeManifest(slug, m);

  console.log(`
${log.bold("published to the Webcules library:")}`)
  console.log(`  library   : http://localhost:3000/components  (apps/landing)`);
  console.log(`  docs page : http://localhost:3000/components/${name}`);
  console.log(`  shadcn    : npx shadcn@latest add http://localhost:3000/r/${name}.json`);
  console.log(`  registry  : apps/landing/public/r/${name}.json (+ zip in webcules/social/${slug}/downloads/)`);
  console.log("nothing is deployed — run the landing deploy when you want it public");
}
