import fs from "node:fs";
import path from "node:path";
import { APP_ROOT, log, type Args } from "./util.ts";

const DEMOS_DIR = path.join(APP_ROOT, "demos");

type DemoMeta = { slug: string; title: string; component: string; description: string };

/** Scans src/demos/*.tsx for `export const meta = { slug, title, component, description }` and rewrites registry.ts. */
export async function cmdSync(_args: Args) {
  if (!fs.existsSync(DEMOS_DIR)) fs.mkdirSync(DEMOS_DIR, { recursive: true });
  const found: DemoMeta[] = [];
  for (const f of fs.readdirSync(DEMOS_DIR).sort()) {
    if (!f.endsWith(".tsx")) continue;
    const src = fs.readFileSync(path.join(DEMOS_DIR, f), "utf8");
    const m = src.match(/export\s+const\s+meta\s*=\s*\{([\s\S]*?)\}\s*;?/);
    if (!m) {
      log.warn(`${f}: no exported meta — skipped`);
      continue;
    }
    const grab = (k: string) => src.match(new RegExp(`${k}\\s*:\\s*["'\`]([^"'\`]+)["'\`]`))?.[1] ?? "";
    found.push({
      slug: grab("slug") || f.replace(/\.tsx$/, ""),
      title: grab("title") || f.replace(/\.tsx$/, ""),
      component: grab("component"),
      description: grab("description"),
    });
  }

  const lines = [
    `// generated by: social sync — do not edit by hand (add/edit demos in src/demos/<slug>.tsx, then re-run)`,
    `import type { ComponentType } from "react";`,
    ``,
    `export type DemoEntry = {`,
    `  meta: DemoMeta;`,
    `  load: () => Promise<{ default: ComponentType<{ variant?: string; layout?: string; hook?: string; panel?: boolean }> }>;`,
    `};`,
    `export type DemoMeta = { slug: string; title: string; component: string; description: string };`,
    ``,
    `export const demos: Record<string, DemoEntry> = {`,
    ...found.map(
      (d) =>
        `  ${JSON.stringify(d.slug)}: { meta: ${JSON.stringify(d, null, 2).replaceAll("\n", "\n    ")}, load: () => import(${JSON.stringify(`./${d.slug}.tsx`)}) },`,
    ),
    `};`,
    ``,
  ];
  fs.writeFileSync(path.join(DEMOS_DIR, "registry.ts"), lines.join("\n"));
  log.ok(`registry.ts: ${found.length} demo(s) — ${found.map((d) => d.slug).join(", ") || "none"}`);
}
