/* GENERATED by tools/upload-samples.mjs from tools/sample-pack.json — do
 * not edit. The Template Studio sample photography (AI-generated, SDXL — no
 * model release required, never attributed to a real studio; license note
 * lives in the manifest). The harness + preview pipeline render templates
 * against these; galleries never ship them. */

export type SamplePhoto = {
  id: string;
  genre: SampleGenre;
  filename: string;
  /** 480px derivative (grid tiles). */
  thumb: string;
  /** 2048px derivative (heroes/previews). */
  web: string;
  width: number;
  height: number;
};

export const SAMPLE_GENRES = ["wedding","family","party","newborn","corporate","editorial"] as const;
export type SampleGenre = (typeof SAMPLE_GENRES)[number];

export const SAMPLE_PACK: Record<SampleGenre, SamplePhoto[]> = {
  "wedding": [
    { id: "wedding-01", genre: "wedding", filename: "wedding-01.jpg", thumb: "/api/pack/samples/wedding/thumb/wedding-01.jpg", web: "/api/pack/samples/wedding/web/wedding-01.jpg", width: 2048, height: 1170 },
    { id: "wedding-02", genre: "wedding", filename: "wedding-02.jpg", thumb: "/api/pack/samples/wedding/thumb/wedding-02.jpg", web: "/api/pack/samples/wedding/web/wedding-02.jpg", width: 1401, height: 2048 },
    { id: "wedding-03", genre: "wedding", filename: "wedding-03.jpg", thumb: "/api/pack/samples/wedding/thumb/wedding-03.jpg", web: "/api/pack/samples/wedding/web/wedding-03.jpg", width: 2048, height: 1401 },
    { id: "wedding-04", genre: "wedding", filename: "wedding-04.jpg", thumb: "/api/pack/samples/wedding/thumb/wedding-04.jpg", web: "/api/pack/samples/wedding/web/wedding-04.jpg", width: 1401, height: 2048 },
    { id: "wedding-05", genre: "wedding", filename: "wedding-05.jpg", thumb: "/api/pack/samples/wedding/thumb/wedding-05.jpg", web: "/api/pack/samples/wedding/web/wedding-05.jpg", width: 2048, height: 1170 },
    { id: "wedding-06", genre: "wedding", filename: "wedding-06.jpg", thumb: "/api/pack/samples/wedding/thumb/wedding-06.jpg", web: "/api/pack/samples/wedding/web/wedding-06.jpg", width: 2048, height: 1170 },
    { id: "wedding-07", genre: "wedding", filename: "wedding-07.jpg", thumb: "/api/pack/samples/wedding/thumb/wedding-07.jpg", web: "/api/pack/samples/wedding/web/wedding-07.jpg", width: 1593, height: 2048 },
    { id: "wedding-08", genre: "wedding", filename: "wedding-08.jpg", thumb: "/api/pack/samples/wedding/thumb/wedding-08.jpg", web: "/api/pack/samples/wedding/web/wedding-08.jpg", width: 2048, height: 1401 },
    { id: "wedding-09", genre: "wedding", filename: "wedding-09.jpg", thumb: "/api/pack/samples/wedding/thumb/wedding-09.jpg", web: "/api/pack/samples/wedding/web/wedding-09.jpg", width: 1593, height: 2048 },
    { id: "wedding-10", genre: "wedding", filename: "wedding-10.jpg", thumb: "/api/pack/samples/wedding/thumb/wedding-10.jpg", web: "/api/pack/samples/wedding/web/wedding-10.jpg", width: 2048, height: 1170 },
  ],
  "family": [
    { id: "family-01", genre: "family", filename: "family-01.jpg", thumb: "/api/pack/samples/family/thumb/family-01.jpg", web: "/api/pack/samples/family/web/family-01.jpg", width: 2048, height: 1170 },
    { id: "family-02", genre: "family", filename: "family-02.jpg", thumb: "/api/pack/samples/family/thumb/family-02.jpg", web: "/api/pack/samples/family/web/family-02.jpg", width: 2048, height: 1170 },
    { id: "family-03", genre: "family", filename: "family-03.jpg", thumb: "/api/pack/samples/family/thumb/family-03.jpg", web: "/api/pack/samples/family/web/family-03.jpg", width: 1401, height: 2048 },
    { id: "family-04", genre: "family", filename: "family-04.jpg", thumb: "/api/pack/samples/family/thumb/family-04.jpg", web: "/api/pack/samples/family/web/family-04.jpg", width: 1593, height: 2048 },
    { id: "family-05", genre: "family", filename: "family-05.jpg", thumb: "/api/pack/samples/family/thumb/family-05.jpg", web: "/api/pack/samples/family/web/family-05.jpg", width: 1593, height: 2048 },
    { id: "family-06", genre: "family", filename: "family-06.jpg", thumb: "/api/pack/samples/family/thumb/family-06.jpg", web: "/api/pack/samples/family/web/family-06.jpg", width: 2048, height: 1170 },
    { id: "family-07", genre: "family", filename: "family-07.jpg", thumb: "/api/pack/samples/family/thumb/family-07.jpg", web: "/api/pack/samples/family/web/family-07.jpg", width: 2048, height: 1401 },
    { id: "family-08", genre: "family", filename: "family-08.jpg", thumb: "/api/pack/samples/family/thumb/family-08.jpg", web: "/api/pack/samples/family/web/family-08.jpg", width: 1401, height: 2048 },
    { id: "family-09", genre: "family", filename: "family-09.jpg", thumb: "/api/pack/samples/family/thumb/family-09.jpg", web: "/api/pack/samples/family/web/family-09.jpg", width: 2048, height: 1170 },
    { id: "family-10", genre: "family", filename: "family-10.jpg", thumb: "/api/pack/samples/family/thumb/family-10.jpg", web: "/api/pack/samples/family/web/family-10.jpg", width: 2048, height: 1401 },
  ],
  "party": [
    { id: "party-01", genre: "party", filename: "party-01.jpg", thumb: "/api/pack/samples/party/thumb/party-01.jpg", web: "/api/pack/samples/party/web/party-01.jpg", width: 2048, height: 1170 },
    { id: "party-02", genre: "party", filename: "party-02.jpg", thumb: "/api/pack/samples/party/thumb/party-02.jpg", web: "/api/pack/samples/party/web/party-02.jpg", width: 2048, height: 1170 },
    { id: "party-03", genre: "party", filename: "party-03.jpg", thumb: "/api/pack/samples/party/thumb/party-03.jpg", web: "/api/pack/samples/party/web/party-03.jpg", width: 2048, height: 1401 },
    { id: "party-04", genre: "party", filename: "party-04.jpg", thumb: "/api/pack/samples/party/thumb/party-04.jpg", web: "/api/pack/samples/party/web/party-04.jpg", width: 1401, height: 2048 },
    { id: "party-05", genre: "party", filename: "party-05.jpg", thumb: "/api/pack/samples/party/thumb/party-05.jpg", web: "/api/pack/samples/party/web/party-05.jpg", width: 2048, height: 1170 },
    { id: "party-06", genre: "party", filename: "party-06.jpg", thumb: "/api/pack/samples/party/thumb/party-06.jpg", web: "/api/pack/samples/party/web/party-06.jpg", width: 2048, height: 1401 },
    { id: "party-07", genre: "party", filename: "party-07.jpg", thumb: "/api/pack/samples/party/thumb/party-07.jpg", web: "/api/pack/samples/party/web/party-07.jpg", width: 2048, height: 1170 },
    { id: "party-08", genre: "party", filename: "party-08.jpg", thumb: "/api/pack/samples/party/thumb/party-08.jpg", web: "/api/pack/samples/party/web/party-08.jpg", width: 1593, height: 2048 },
    { id: "party-09", genre: "party", filename: "party-09.jpg", thumb: "/api/pack/samples/party/thumb/party-09.jpg", web: "/api/pack/samples/party/web/party-09.jpg", width: 1401, height: 2048 },
    { id: "party-10", genre: "party", filename: "party-10.jpg", thumb: "/api/pack/samples/party/thumb/party-10.jpg", web: "/api/pack/samples/party/web/party-10.jpg", width: 2048, height: 1170 },
  ],
  "newborn": [
    { id: "newborn-01", genre: "newborn", filename: "newborn-01.jpg", thumb: "/api/pack/samples/newborn/thumb/newborn-01.jpg", web: "/api/pack/samples/newborn/web/newborn-01.jpg", width: 1593, height: 2048 },
    { id: "newborn-02", genre: "newborn", filename: "newborn-02.jpg", thumb: "/api/pack/samples/newborn/thumb/newborn-02.jpg", web: "/api/pack/samples/newborn/web/newborn-02.jpg", width: 2048, height: 1401 },
    { id: "newborn-03", genre: "newborn", filename: "newborn-03.jpg", thumb: "/api/pack/samples/newborn/thumb/newborn-03.jpg", web: "/api/pack/samples/newborn/web/newborn-03.jpg", width: 1593, height: 2048 },
    { id: "newborn-04", genre: "newborn", filename: "newborn-04.jpg", thumb: "/api/pack/samples/newborn/thumb/newborn-04.jpg", web: "/api/pack/samples/newborn/web/newborn-04.jpg", width: 2048, height: 1401 },
    { id: "newborn-05", genre: "newborn", filename: "newborn-05.jpg", thumb: "/api/pack/samples/newborn/thumb/newborn-05.jpg", web: "/api/pack/samples/newborn/web/newborn-05.jpg", width: 1401, height: 2048 },
    { id: "newborn-06", genre: "newborn", filename: "newborn-06.jpg", thumb: "/api/pack/samples/newborn/thumb/newborn-06.jpg", web: "/api/pack/samples/newborn/web/newborn-06.jpg", width: 2048, height: 2048 },
    { id: "newborn-07", genre: "newborn", filename: "newborn-07.jpg", thumb: "/api/pack/samples/newborn/thumb/newborn-07.jpg", web: "/api/pack/samples/newborn/web/newborn-07.jpg", width: 2048, height: 1401 },
    { id: "newborn-08", genre: "newborn", filename: "newborn-08.jpg", thumb: "/api/pack/samples/newborn/thumb/newborn-08.jpg", web: "/api/pack/samples/newborn/web/newborn-08.jpg", width: 1401, height: 2048 },
    { id: "newborn-09", genre: "newborn", filename: "newborn-09.jpg", thumb: "/api/pack/samples/newborn/thumb/newborn-09.jpg", web: "/api/pack/samples/newborn/web/newborn-09.jpg", width: 2048, height: 2048 },
    { id: "newborn-10", genre: "newborn", filename: "newborn-10.jpg", thumb: "/api/pack/samples/newborn/thumb/newborn-10.jpg", web: "/api/pack/samples/newborn/web/newborn-10.jpg", width: 2048, height: 1401 },
  ],
  "corporate": [
    { id: "corporate-01", genre: "corporate", filename: "corporate-01.jpg", thumb: "/api/pack/samples/corporate/thumb/corporate-01.jpg", web: "/api/pack/samples/corporate/web/corporate-01.jpg", width: 2048, height: 1170 },
    { id: "corporate-02", genre: "corporate", filename: "corporate-02.jpg", thumb: "/api/pack/samples/corporate/thumb/corporate-02.jpg", web: "/api/pack/samples/corporate/web/corporate-02.jpg", width: 1401, height: 2048 },
    { id: "corporate-03", genre: "corporate", filename: "corporate-03.jpg", thumb: "/api/pack/samples/corporate/thumb/corporate-03.jpg", web: "/api/pack/samples/corporate/web/corporate-03.jpg", width: 2048, height: 1170 },
    { id: "corporate-04", genre: "corporate", filename: "corporate-04.jpg", thumb: "/api/pack/samples/corporate/thumb/corporate-04.jpg", web: "/api/pack/samples/corporate/web/corporate-04.jpg", width: 2048, height: 1401 },
    { id: "corporate-05", genre: "corporate", filename: "corporate-05.jpg", thumb: "/api/pack/samples/corporate/thumb/corporate-05.jpg", web: "/api/pack/samples/corporate/web/corporate-05.jpg", width: 2048, height: 1170 },
    { id: "corporate-06", genre: "corporate", filename: "corporate-06.jpg", thumb: "/api/pack/samples/corporate/thumb/corporate-06.jpg", web: "/api/pack/samples/corporate/web/corporate-06.jpg", width: 2048, height: 1170 },
    { id: "corporate-07", genre: "corporate", filename: "corporate-07.jpg", thumb: "/api/pack/samples/corporate/thumb/corporate-07.jpg", web: "/api/pack/samples/corporate/web/corporate-07.jpg", width: 1401, height: 2048 },
    { id: "corporate-08", genre: "corporate", filename: "corporate-08.jpg", thumb: "/api/pack/samples/corporate/thumb/corporate-08.jpg", web: "/api/pack/samples/corporate/web/corporate-08.jpg", width: 1593, height: 2048 },
    { id: "corporate-09", genre: "corporate", filename: "corporate-09.jpg", thumb: "/api/pack/samples/corporate/thumb/corporate-09.jpg", web: "/api/pack/samples/corporate/web/corporate-09.jpg", width: 2048, height: 1401 },
    { id: "corporate-10", genre: "corporate", filename: "corporate-10.jpg", thumb: "/api/pack/samples/corporate/thumb/corporate-10.jpg", web: "/api/pack/samples/corporate/web/corporate-10.jpg", width: 2048, height: 1401 },
  ],
  "editorial": [
    { id: "editorial-01", genre: "editorial", filename: "editorial-01.jpg", thumb: "/api/pack/samples/editorial/thumb/editorial-01.jpg", web: "/api/pack/samples/editorial/web/editorial-01.jpg", width: 1401, height: 2048 },
    { id: "editorial-02", genre: "editorial", filename: "editorial-02.jpg", thumb: "/api/pack/samples/editorial/thumb/editorial-02.jpg", web: "/api/pack/samples/editorial/web/editorial-02.jpg", width: 1401, height: 2048 },
    { id: "editorial-03", genre: "editorial", filename: "editorial-03.jpg", thumb: "/api/pack/samples/editorial/thumb/editorial-03.jpg", web: "/api/pack/samples/editorial/web/editorial-03.jpg", width: 1593, height: 2048 },
    { id: "editorial-04", genre: "editorial", filename: "editorial-04.jpg", thumb: "/api/pack/samples/editorial/thumb/editorial-04.jpg", web: "/api/pack/samples/editorial/web/editorial-04.jpg", width: 2048, height: 2048 },
    { id: "editorial-05", genre: "editorial", filename: "editorial-05.jpg", thumb: "/api/pack/samples/editorial/thumb/editorial-05.jpg", web: "/api/pack/samples/editorial/web/editorial-05.jpg", width: 1401, height: 2048 },
    { id: "editorial-06", genre: "editorial", filename: "editorial-06.jpg", thumb: "/api/pack/samples/editorial/thumb/editorial-06.jpg", web: "/api/pack/samples/editorial/web/editorial-06.jpg", width: 1593, height: 2048 },
    { id: "editorial-07", genre: "editorial", filename: "editorial-07.jpg", thumb: "/api/pack/samples/editorial/thumb/editorial-07.jpg", web: "/api/pack/samples/editorial/web/editorial-07.jpg", width: 2048, height: 1401 },
    { id: "editorial-08", genre: "editorial", filename: "editorial-08.jpg", thumb: "/api/pack/samples/editorial/thumb/editorial-08.jpg", web: "/api/pack/samples/editorial/web/editorial-08.jpg", width: 1401, height: 2048 },
    { id: "editorial-09", genre: "editorial", filename: "editorial-09.jpg", thumb: "/api/pack/samples/editorial/thumb/editorial-09.jpg", web: "/api/pack/samples/editorial/web/editorial-09.jpg", width: 1593, height: 2048 },
    { id: "editorial-10", genre: "editorial", filename: "editorial-10.jpg", thumb: "/api/pack/samples/editorial/thumb/editorial-10.jpg", web: "/api/pack/samples/editorial/web/editorial-10.jpg", width: 2048, height: 1401 },
  ],
};

/** Every sample photo in a stable order (genres in registry order). */
export const ALL_SAMPLES: SamplePhoto[] = SAMPLE_GENRES.flatMap((g) => SAMPLE_PACK[g]);
