/* GENERATED by tools/render-template-previews.mjs — do not edit.
 * Static, cacheable thumbs for the seed-template picker grid (WEB-319/320):
 * one desktop 1200x900 + mobile 390x844 webp per seed, served immutably from
 * R2 via /api/pack. Regenerate with the tools script after changing a seed. */
export const TEMPLATE_PREVIEWS: Record<string, { desktop: string; mobile: string }> = {
  "classic-wedding": {
    "desktop": "/api/pack/template-previews/classic-wedding/desktop.webp",
    "mobile": "/api/pack/template-previews/classic-wedding/mobile.webp"
  }
};
