/* Shared helpers for the Webcules component forge.
 * Framework-free Node scripts. Windows-safe paths via URL resolution. */
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync, rmSync, copyFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";
import { spawnSync } from "node:child_process";
import { createRequire as createRequireFrom } from "node:module";

const HERE = dirname(fileURLToPath(import.meta.url));
export const ROOT = resolve(HERE, "..", "..", "..");
export const LANDING = join(ROOT, "apps", "landing");
export const UI_PKG = join(ROOT, "packages", "ui", "src", "components");
export const LIBRARY_DIR = join(LANDING, "components", "library");
export const LIBRARY_JSON = join(LIBRARY_DIR, "library.json");
export const MANIFEST_TS = join(LIBRARY_DIR, "manifest.gen.ts");
export const PUBLIC_DIR = join(LANDING, "public");
export const REGISTRY_DIR = join(PUBLIC_DIR, "r");
export const DOCS_DIR = join(LANDING, "app", "(marketing)", "components");

export const log = {
  ok: (...a) => console.log("  ✓", ...a),
  info: (...a) => console.log("  •", ...a),
  warn: (...a) => console.log("  ⚠", ...a),
  err: (...a) => console.error("  ✗", ...a),
};

export function die(msg, hint) {
  log.err(msg);
  if (hint) log.info(hint);
  process.exit(1);
}

export function readJson(path) {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch (e) {
    die(`invalid JSON in ${path}: ${e.message}`);
    return null;
  }
}

export function writeJson(path, data) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(data, null, 2) + "\n");
}

/* ---- library manifest (library.json is the editable source of truth) ---- */
export function readLibrary() {
  if (!existsSync(LIBRARY_JSON)) return { components: [] };
  return readJson(LIBRARY_JSON);
}
export function writeLibrary(lib) {
  mkdirSync(LIBRARY_DIR, { recursive: true });
  writeJson(LIBRARY_JSON, lib);
}
export function getEntry(lib, name) {
  return lib.components.find((c) => c.name === name) || null;
}

/* ---- generated TS manifest consumed by the landing app ---- */
export function writeManifestTs(entries) {
  mkdirSync(LIBRARY_DIR, { recursive: true });
  const banner =
    "/* AUTO-GENERATED by `pnpm forge:approve` — edit library.json instead. */\n";
  const body = `export type LibraryEntry = {
  name: string;
  title: string;
  tagline: string;
  description: string;
  tags: string[];
  premium: boolean;
  phase: "draft" | "approved";
  docsMode: "custom" | "generated";
  preview?: string;
  phrase?: string;
};

export const LIBRARY: LibraryEntry[] = ${JSON.stringify(entries, null, 2)};
`;
  writeFileSync(MANIFEST_TS, banner + body);
}

/* ---- spec validation (lightweight, no deps) ---- */
export function validateSpec(spec) {
  const errs = [];
  if (!spec.name || !/^[a-z][a-z0-9-]*$/.test(spec.name))
    errs.push("name: required, lowercase kebab-case");
  if (!spec.title) errs.push("title: required");
  if (!spec.tagline) errs.push("tagline: required (one-liner for the card)");
  if (!spec.description) errs.push("description: required");
  if (!Array.isArray(spec.tags) || spec.tags.length === 0)
    errs.push("tags: at least one tag");
  if (!spec.breakdown || typeof spec.breakdown !== "object")
    errs.push("breakdown: required object with layers/animation/ux sections");
  else {
    const b = spec.breakdown;
    if (!Array.isArray(b.layers) || b.layers.length === 0)
      errs.push("breakdown.layers: describe the visual layers (back→front)");
    if (!Array.isArray(b.animation) || b.animation.length === 0)
      errs.push("breakdown.animation: describe the animations/motions");
    if (!Array.isArray(b.ux) || b.ux.length === 0)
      errs.push("breakdown.ux: accessibility + interaction notes");
  }
  return errs;
}

export function specPath(name) {
  return join(LIBRARY_DIR, name, "spec.json");
}
export function loadSpec(name) {
  const p = specPath(name);
  if (!existsSync(p)) return null;
  return readJson(p);
}

/* run a command, inherit stdio */
export function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, {
    stdio: "inherit",
    shell: process.platform === "win32",
    ...opts,
  });
  return r.status === 0;
}
export const requireFromLanding = createRequireFrom(
  join(LANDING, "package.json"),
);

export { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync, statSync, rmSync, copyFileSync, join, resolve, dirname };
export { pathToFileURL };
